name: Publish Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          npm i
      - name: Build Website
        run: |
          npm run build
      - name: Deploy Website
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.address}}
          webdav_username: ${{secrets.username}}
          webdav_password: ${{secrets.password}}
          webdav_upload_path: "/me"
          files: "./dist/**"
